name: Simple Update code and restart backend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: SSH Deploy with Debug
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.KEY }}
          port: 22
          script: |
            cd ${{ secrets.PATH }}
            git pull origin main
            git submodule update --remote --merge
            export JWT_SECRET_KEY=${{ secrets.JWT_SECRET }}
            export POSTGRES_DB=${{ secrets.DB_NAME }}
            export POSTGRES_USER=${{ secrets.DB_USER }}
            export POSTGRES_PASSWORD=${{ secrets.DB_PASSWORD }}
            docker compose up -d
          debug: true  # üí• –≠—Ç–æ –ø–æ–∫–∞–∂–µ—Ç –≤—Å–µ –∫–æ–º–∞–Ω–¥—ã –∏ –ø–æ–¥–∫–ª—é—á–µ–Ω–∏—è
